### ISSUE TITLE
How to get image features of my own dataset

### ISSUE THREAD

**Issue by StevenTang1998** [VegB/iNLG#1]
Thanks for contributing such interesting and meaningful work!

Your codes work great, and I wonder how I can use the code for my own dataset. I noticed you have processed `vitb32.hdf5` for each dataset, which contains a 512-dimensional ViT feature for each image. So could you give some official instructions to create a `vitb32.hdf5` for my own dataset?

**Comment by VegB** [comment]
Thanks for asking! I just updated the script to extract CLIP features [here](https://github.com/VegB/iNLG/blob/main/scripts/extract_visual_features.py).
Hope it helps :)

**Comment by StevenTang1998** [comment]
Thanks for the prompt response.

I also wonder if there is a script to get images from input texts using VQGAN or OFA.

**Comment by VegB** [comment]
We were using the following official implementations to render images from text with VQGAN & OFA.
- `VQGAN+CLIP`: https://github.com/nerdyrodent/VQGAN-CLIP
- `OFA`: https://github.com/OFA-Sys/OFA

**Comment by StevenTang1998** [comment]
Thanks very much for your kind help!!! I'll have a try!
Good day!

**Comment by VegB** [comment]
Good luck! I'll close this issue for now
