### ISSUE TITLE
A bug in generation

### ISSUE THREAD

**Issue by StevenTang1998** [VegB/iNLG#2]
Hi, I found the code may be wrong.
https://github.com/VegB/iNLG/blob/96800ea8ff27cad4545380eabf665e6910a780eb/code/trainer.py#L134

First, if `self` does not have an attribute `_max_length`, directly calling `self._max_length` leads to an error.
So, I changed it to `hasattr(self, '_max_length')`.

After that I found this condition always goes to the else option, so the `max_length` will be `model.config.max_length`, which equals 20 by default. I think it should `args.max_output_length`, or it may cause a truncation when the task is story generation.

**Comment by VegB** [comment]
Hi,

I'm trying to look into this issue. 
May I confirm the `transformers` version and the command you are using to reproduce this error?
Just checked my output results, and I didn't witness any truncation when generating stories.

**Comment by VegB** [comment]
Hi,

I figure out what happens. Ok so first of all, this repo is built upon `transformers==4.16.2`.

The `CLIPCapTrainer` we are using is inherited from `Seq2SeqTrainer`, and the latter sets `self._max_length` when calling [self.evaluate()](https://github.com/huggingface/transformers/blob/v4.16.2-release/src/transformers/trainer_seq2seq.py#L68) or [self.predict()](https://github.com/huggingface/transformers/blob/v4.16.2-release/src/transformers/trainer_seq2seq.py#L117). The self-defined trainer class in the repo doesn't override the evaluate/predict function, which means the behavior should be the same as Seq2SeqTrainer. More specifically, when we call the trainer's predict function [here](https://github.com/VegB/iNLG/blob/96800ea8ff27cad4545380eabf665e6910a780eb/code/evaluate.py#L9), we are actually setting the attribute of `_max_length` to `args.max_output_length`. 

Still, I agree that the "else condition" here is pretty confusing (even though we are actually not using it during inference). I just fixed this (see: [link](https://github.com/VegB/iNLG/blob/main/code/trainer.py#L134)).

**Comment by StevenTang1998** [comment]
Got it. My transformer version is a bit different. Thanks very much for your help!
